name: banking_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  equatable: ^2.0.5
  zoom_tap_animation: ^1.1.0
  sqflite: ^2.2.5
  google_fonts: ^4.0.3
  mask_text_input_formatter: ^2.4.0
  month_year_picker: ^0.2.0+3
  flutter_material_color_picker: ^1.1.0+2
  shared_preferences: ^2.0.18
  firebase_messaging: ^14.2.5
  firebase_core: ^2.3.0
  flutter_local_notifications: ^13.0.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  adaptive_theme: ^3.1.1
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

